/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 58
#define YY_END_OF_BUFFER 59
static yyconst short int yy_accept[165] =
    {   0,
        0,    0,   59,   58,    2,    1,   42,   58,   35,   58,
       58,   23,   24,   33,   31,   30,   32,   34,   43,   29,
       39,   36,   39,   56,   27,   28,   58,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   25,   58,   26,
        2,   39,    0,   19,    0,   40,    0,    0,   37,   38,
        0,   21,    0,   43,    0,   57,   56,   56,   56,    0,
       56,   56,   56,   56,   56,    7,   56,   56,   56,    3,
       56,   56,   56,   56,   56,   41,    0,    0,    0,   45,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   21,   44,    0,   44,   57,   57,   56,   56,

       56,   56,   56,   56,   56,   56,    5,    9,   56,   56,
       56,   56,    0,   19,    0,    0,   20,    0,    0,    0,
       55,   48,   50,   53,   51,   46,   52,   47,   54,    0,
       22,   56,   16,   10,   56,   56,   56,    4,   56,   56,
       56,   13,   56,    0,    0,    0,    8,   56,   56,   56,
       11,   56,   56,    6,   49,   56,   56,   12,   14,   15,
       56,   17,   18,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    2,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    6,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,    1,   20,   21,
       22,   23,    1,    1,   24,   24,   24,   24,   25,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       26,   27,   28,    1,   29,    1,   30,   31,   32,   33,

       34,   35,   24,   36,   37,   24,   38,   39,   24,   40,
       41,   24,   24,   42,   43,   44,   45,   46,   47,   24,
       24,   24,   48,   49,   50,    1,    1,   51,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   52,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   53,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[54] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    1,    3,    3,    1,
        1,    1,    1,    4,    4,    1,    1,    1,    5,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    1,    1,    1,
        1,    1,    1
    } ;

static yyconst short int yy_base[177] =
    {   0,
        0,    0,  397,  517,   52,  517,  373,   50,  517,  379,
      334,  517,  517,  517,  345,  517,  340,   44,   41,  517,
      332,  313,  296,   52,  517,  517,  286,   66,   50,   47,
       23,   54,   34,   56,   31,   22,   58,  517,  255,  517,
       85,  517,   92,   94,  104,  517,  292,  130,  517,  517,
      263,    0,   83,   95,  109,  124,  109,  110,  222,  217,
      129,  138,  117,  150,  152,  161,  169,  163,  172,  180,
      183,  191,  192,  194,  203,  517,  105,  157,  188,  517,
      230,  219,  217,  209,  204,  192,  173,  155,  146,  102,
      122,  129,    0,  198,   99,  131,  231,  235,  214,  232,

      236,  249,  252,  253,  254,  255,  256,  257,  261,  270,
      274,  286,  168,  197,  278,  216,  252,  284,  295,  305,
      517,  517,  517,  517,  517,  517,  517,  517,  517,   54,
       71,  303,  307,  311,  314,  315,  320,  323,  327,  328,
      331,  332,  334,  319,  361,   58,  336,  361,  366,  373,
      369,  374,  377,  375,  517,  378,  380,  386,  393,  394,
      415,  421,  423,  517,  465,  470,  473,  474,  479,  484,
      489,  492,  496,  501,  506,  511
    } ;

static yyconst short int yy_def[177] =
    {   0,
      164,    1,  164,  164,  164,  164,  164,  165,  164,  164,
      166,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  167,  164,  164,  168,  167,   28,   28,
       28,   28,   28,   28,   28,   28,   28,  164,  164,  164,
      164,  164,  165,  165,  169,  164,  164,  164,  164,  164,
      170,  171,  164,  164,  164,  172,   28,   28,   28,  168,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,  164,  173,  174,  175,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      170,  170,  171,  164,  164,  164,  172,  172,   28,   28,

       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,  173,  173,  175,  174,  174,  176,  173,  175,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      170,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,  174,  176,  164,   28,   28,   28,   28,
       28,   28,   28,   28,  164,   28,   28,   28,   28,   28,
       28,   28,   28,    0,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164
    } ;

static yyconst short int yy_nxt[571] =
    {   0,
        4,    5,    6,    7,    8,    4,    9,   10,   11,   12,
       13,   14,   15,   16,   17,    4,   18,   19,   19,   20,
       21,   22,   23,   24,   24,   25,    5,   26,   27,   24,
       28,   29,   30,   31,   32,   24,   33,   24,   24,   24,
       24,   34,   35,   24,   24,   36,   37,   38,   39,   40,
        5,    5,    5,   41,   44,   51,   53,   56,   54,   54,
       52,   67,   74,   58,   58,   55,  155,   56,   70,   57,
       57,   56,   58,   71,   55,   58,   45,   73,   41,   62,
       65,   56,   92,   57,   57,   63,   41,   66,   58,   72,
       64,   58,   68,   75,   69,   58,   44,   58,   44,   58,

       94,   94,   41,   41,   41,  146,   78,   61,   44,  114,
       53,   41,   54,   54,  164,  164,   96,   96,   45,   55,
       45,   95,  164,   95,  164,  164,   96,   96,   55,   56,
       79,  115,  164,   92,  164,   41,   41,   41,   80,   56,
       92,   97,   97,  164,  164,  131,  101,   81,   96,   96,
       58,   58,  130,  164,  129,  164,   82,  164,   58,   83,
       84,  117,   99,  128,   85,  164,  164,  164,  164,   86,
       58,   87,  114,   88,  164,   89,  164,  164,  164,   58,
      100,  127,   90,  118,  164,  164,  103,  164,  164,  102,
       78,   58,  114,   58,  115,  164,  164,  164,  164,  164,

      126,  114,   58,  106,   58,  104,  164,  164,  164,  164,
       58,  105,  125,  107,  120,   94,   94,  124,  164,  164,
      117,   58,   55,  115,   58,  123,  108,  122,  110,  164,
      111,   55,   58,   58,  109,   58,  164,  164,  121,  112,
      164,  164,  118,  132,   58,   60,  164,  164,   97,   97,
      164,  164,   97,   97,  164,   58,  117,  164,  164,  164,
      164,  164,  164,   58,  164,  133,  164,  164,  164,  164,
      164,  164,  164,   58,   92,  164,  164,  134,  118,  164,
       78,  136,  114,  137,  139,  164,   78,  138,  117,  164,
       58,  164,  135,   58,   58,   58,   58,   58,   58,  114,

       80,  164,   58,   76,  120,  140,  142,   78,  164,  114,
      145,   58,  164,  141,   60,   58,  164,   42,  164,  164,
      164,  115,  164,  117,  143,  164,  164,   58,  164,  164,
      164,  120,  164,  164,   42,  164,  164,  164,  164,  164,
      147,  164,  164,  164,   58,  118,  164,  164,   58,  164,
      148,  164,   58,   42,   50,   58,   58,   49,  150,  149,
       48,   58,  153,   78,   58,  117,  164,  154,   58,  152,
      151,  164,   58,   58,  164,   58,  164,   58,  164,  164,
      164,  164,  164,  164,  164,  164,   46,  145,  164,  164,
      164,  164,  164,  164,   42,  164,  164,  164,  164,  164,

      156,  164,   58,  164,  157,  164,  158,   58,  164,  164,
       58,  164,  160,  159,   58,   58,   58,  164,   58,   58,
      164,   58,  161,  162,  164,  164,  164,   58,  164,  164,
      164,  164,  164,  164,   58,   58,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  163,  164,
      164,  164,  164,  164,  164,  164,   58,  164,  164,  164,
      164,  164,   58,  164,   58,   43,  164,   43,   43,   43,
       47,  164,   47,   47,   47,   58,   58,   59,   59,   77,
       77,   77,   77,   77,   91,   91,   91,   91,   91,   93,
      164,   93,   93,   93,   98,   98,  113,  164,  113,  113,

      113,  116,  164,  116,  116,  116,  119,  119,  119,  119,
      119,  144,  144,  144,  144,  144,    3,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164
    } ;

static yyconst short int yy_chk[571] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    5,    8,   18,   19,   24,   19,   19,
       18,   31,   36,   36,   31,   19,  146,   24,   33,   24,
       24,   28,   35,   33,   19,   33,    8,   35,    5,   29,
       30,   28,  131,   28,   28,   29,   41,   30,   30,   34,
       29,   29,   32,   37,   32,   32,   43,   34,   44,   37,

       53,   53,    5,    5,    5,  130,   45,   28,   45,   77,
       54,   41,   54,   54,   57,   58,   95,   95,   43,   54,
       44,   55,   63,   55,   57,   58,   55,   55,   54,   56,
       45,   77,   63,   91,   61,   41,   41,   41,   48,   56,
       92,   56,   56,   62,   61,   92,   63,   48,   96,   96,
       57,   58,   90,   62,   89,   64,   48,   65,   63,   48,
       48,   78,   61,   88,   48,   64,   66,   65,   68,   48,
       61,   48,  113,   48,   67,   48,   66,   69,   68,   62,
       62,   87,   48,   78,   67,   70,   65,   69,   71,   64,
       79,   64,   79,   65,  113,   70,   72,   73,   71,   74,

       86,  114,   66,   68,   68,   66,   72,   73,   75,   74,
       67,   67,   85,   69,   79,   94,   94,   84,   75,   99,
      116,   70,   94,  114,   71,   83,   71,   82,   73,   99,
       74,   94,   72,   73,   72,   74,   97,  100,   81,   75,
       98,  101,  116,   99,   75,   60,   97,  100,   97,   97,
       98,  101,   98,   98,  102,   99,  117,  103,  104,  105,
      106,  107,  108,   59,  102,  100,  109,  103,  104,  105,
      106,  107,  108,  100,   51,  110,  109,  101,  117,  111,
      115,  103,  115,  104,  106,  110,  118,  105,  118,  111,
      102,  112,  102,  103,  104,  105,  106,  107,  108,  119,

       47,  112,  109,   39,  115,  109,  111,  120,  132,  120,
      118,  110,  133,  110,   27,  111,  134,   23,  132,  135,
      136,  119,  133,  144,  112,  137,  134,  112,  138,  135,
      136,  120,  139,  140,   22,  137,  141,  142,  138,  143,
      132,  147,  139,  140,  132,  144,  141,  142,  133,  143,
      135,  147,  134,   21,   17,  135,  136,   15,  137,  136,
       11,  137,  141,  145,  138,  145,  148,  143,  139,  140,
      139,  149,  141,  142,  151,  143,  148,  147,  150,  152,
      154,  149,  153,  156,  151,  157,   10,  145,  150,  152,
      154,  158,  153,  156,    7,  157,    3,    0,  159,  160,

      148,  158,  148,    0,  149,    0,  150,  149,  159,  160,
      151,    0,  153,  152,  150,  152,  154,    0,  153,  156,
      161,  157,  156,  157,    0,    0,  162,  158,  163,    0,
      161,    0,    0,    0,  159,  160,  162,    0,  163,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  161,    0,
        0,    0,    0,    0,    0,    0,  161,    0,    0,    0,
        0,    0,  162,    0,  163,  165,    0,  165,  165,  165,
      166,    0,  166,  166,  166,  167,  167,  168,  168,  169,
      169,  169,  169,  169,  170,  170,  170,  170,  170,  171,
        0,  171,  171,  171,  172,  172,  173,    0,  173,  173,

      173,  174,    0,  174,  174,  174,  175,  175,  175,  175,
      175,  176,  176,  176,  176,  176,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "shams.l"
#define INITIAL 0
#line 4 "shams.l"
#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include<iostream>
#include<string>
#include<list>
#define SIZE 500
#define MOD 500
using namespace std;

int arr[SIZE];

int line_count=1;
int error_count=0;

FILE *logout;
FILE *tokenout;


int hash_func(string str)
{
    int i,len=str.length();
    int hash=0;
    for(i=0; i<len; i++)
    {
        hash += str[i]^i * 27;
        hash %= MOD;
    }
    return hash;
}

class symbolInfo
{
public:
    string item;
    string type;

    symbolInfo(string names, string val)
    {
		
		item=names;
		type=val;		

    }


};


class symbolTable
{
public:
    list <symbolInfo> stable[SIZE];
	
    list<symbolInfo>::iterator it;

    void input(symbolInfo obj)
    {
        int index, counter;
		
        index = Search(obj.item);
		
        if(index==-1)
        {
			int i;
			char *itm,*tp;
			itm=new char[obj.item.length()];
			for ( i=0;i<obj.item.length();i++){
			itm[i]=obj.item[i];
			}
			itm[i]='\0';
			tp=new char[obj.type.length()];
			for ( i=0;i<obj.type.length();i++){
			tp[i]=obj.type[i];
			}
			tp[i]='\0';
			fprintf(logout,"<%s,%s> already exits\n",itm, tp);
		           			
        }
		else
		{
			arr[index]=1;
			stable[index].push_back(obj);
		}

    }

	void print()
    {
        for(int index = 0; index<SIZE; index++)
        {
            if(arr[index]!=0)
            {
                
                fprintf(logout,"%d ->",index);
                for(it=stable[index].begin(); it!=stable[index].end(); it++)
                    {
						int i;
						char *itm,*tp;
						int itemsz=it->item.length();
						int typesz=it->type.length();
						itm=new char[itemsz+1];
						for ( i=0;i<itemsz;i++){
						itm[i]=it->item[i];
						}
						itm[i]='\0';
						tp=new char[typesz+1];
						for ( i=0;i<typesz;i++){
						tp[i]=it->type[i];
						}
						tp[i]='\0';
						fprintf(logout,"<%s,%s>",itm, tp);
						
						
                    	
                    }


                fprintf(logout,"\n");

            }
        }
        fprintf(logout,"\n\n");
    }
	
	int Search(string s)
    {
		int index=hash_func(s); 
        
        if(arr[index])
        {
            for(it=stable[index].begin(); it!=stable[index].end(); it++)
            {
                if(s== it->item)
                {
                    return -1;
                }
            }
        }
        
        return index;
    }
}symtab;



/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 171 "shams.l"



	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 165 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 517 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 173 "shams.l"
{		line_count++;
				printf("\n");
			}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 176 "shams.l"
{}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 178 "shams.l"
{
				fprintf(tokenout,"<IF>");
				fprintf(logout,"Line no %d: TOKEN <IF> Lexeme %s found\n\n",line_count,yytext);
				 
			}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 184 "shams.l"
{
				fprintf(tokenout,"<ELSE>");
				fprintf(logout,"Line no %d: TOKEN <ELSE> Lexeme %s found\n\n",line_count,yytext);
				 
			}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 190 "shams.l"
{
				fprintf(tokenout,"<FOR>");
				fprintf(logout,"Line no %d: TOKEN <FOR> Lexeme %s found\n\n",line_count,yytext);
				 
			}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 195 "shams.l"
{
				fprintf(tokenout,"<WHILE>");
				fprintf(logout,"Line no %d: TOKEN <WHILE> Lexeme %s found\n\n",line_count,yytext);
				 
			}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 200 "shams.l"
{
				fprintf(tokenout,"<DO>");
				fprintf(logout,"Line no %d: TOKEN <DO> Lexeme %s found\n\n",line_count,yytext);
				 
			} 
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 205 "shams.l"
{
				fprintf(tokenout,"<BREAK>");
				fprintf(logout,"Line no %d: TOKEN <BREAK> Lexeme %s found\n\n",line_count,yytext);
				 
			}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 210 "shams.l"
{
				fprintf(tokenout,"<INT>");
				fprintf(logout,"Line no %d: TOKEN <INT> Lexeme %s found\n\n",line_count,yytext);
				 
			} 
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 215 "shams.l"
{
				fprintf(tokenout,"<CHAR>");
				fprintf(logout,"Line no %d: TOKEN <CHAR> Lexeme %s found\n\n",line_count,yytext);
				 
			}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 220 "shams.l"
{
				fprintf(tokenout,"<FLOAT>");
				fprintf(logout,"Line no %d: TOKEN <FLOAT> Lexeme %s found\n\n",line_count,yytext);
				 
			} 
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 225 "shams.l"
{
				fprintf(tokenout,"<DOUBLE>");
				fprintf(logout,"Line no %d: TOKEN <DOUBLE> Lexeme %s found\n\n",line_count,yytext);
				 
			}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 230 "shams.l"
{
				fprintf(tokenout,"<VOID>");
				fprintf(logout,"Line no %d: TOKEN <VOID> Lexeme %s found\n\n",line_count,yytext);
				 
			} 
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 235 "shams.l"
{
				fprintf(tokenout,"<RETURN>");
				fprintf(logout,"Line no %d: TOKEN <RETURN> Lexeme %s found\n\n",line_count,yytext);
				 
			} 
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 240 "shams.l"
{
				fprintf(tokenout,"<SWITCH>");
				fprintf(logout,"Line no %d: TOKEN <SWITCH> Lexeme %s found\n\n",line_count,yytext);
				 
			}  
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 245 "shams.l"
{
				fprintf(tokenout,"<CASE>");
				fprintf(logout,"Line no %d: TOKEN <CASE> Lexeme %s found\n\n",line_count,yytext);
				 
			}  
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 250 "shams.l"
{
				fprintf(tokenout,"<DEFAULT>");
				fprintf(logout,"Line no %d: TOKEN <DEFAULT> Lexeme %s found\n\n",line_count,yytext);
				 
			}   
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 255 "shams.l"
{
				fprintf(tokenout,"<CONTINUE>");
				fprintf(logout,"Line no %d: TOKEN <CONTINUE> Lexeme %s found\n\n",line_count,yytext);
				 
			} 
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 260 "shams.l"
{
				fprintf(tokenout,"<STRING,%s>",yytext);
				fprintf(logout,"Line no %d: TOKEN <STRING> Lexeme %s found\n",line_count,yytext);
				/* */
			}	
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 266 "shams.l"
{

				fprintf(tokenout,"<MULTI_LINE_STRING,%s>",yytext);
				fprintf(logout,"Line no %d: TOKEN <MULTI_LINE_STRING> Lexeme %s found\n",line_count,yytext);
				/* */
			}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 272 "shams.l"
{				
				fprintf(logout,"Line no %d: TOKEN <COMMENT> Lexeme %s found\n",line_count,yytext);
				/* */
			}				
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 277 "shams.l"
{
				
				fprintf(logout,"Line no %d: TOKEN <MULTI_LINE_COMMENT> Lexeme %s found\n",line_count,yytext);
				 
				/*("/*"( [^*] | (\*+[^* /]) )*\*+\/)*/
			}			
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 283 "shams.l"
{
					fprintf(tokenout,"<LPAREN,%s>",yytext);
					fprintf(logout,"Line no %d: TOKEN <LPAREN> Lexeme %s found\n",line_count,yytext);
					 
					symbolInfo symbolIn(yytext,"LPAREN");
					symtab.input(symbolIn);
					symtab.print();
			}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 291 "shams.l"
{
					fprintf(tokenout,"<RPAREN,%s>",yytext);
					fprintf(logout,"Line no %d: TOKEN <RPAREN> Lexeme %s found\n",line_count,yytext);
					 
					symbolInfo symbolIn(yytext,"RPAREN");
					symtab.input(symbolIn);
					symtab.print();
			}	
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 299 "shams.l"
{
					fprintf(tokenout,"<LCURL,%s>",yytext);
					fprintf(logout,"Line no %d: TOKEN <LCURL> Lexeme %s found\n",line_count,yytext);
					 
					symbolInfo symbolIn(yytext,"LCURL");
					symtab.input(symbolIn);
					symtab.print();
			}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 307 "shams.l"
{
					fprintf(tokenout,"<RCURL,%s>",yytext);
					fprintf(logout,"Line no %d: TOKEN <RCURL> Lexeme %s found\n",line_count,yytext);
					 
					symbolInfo symbolIn(yytext,"RCURL");
					symtab.input(symbolIn);
					symtab.print();
			}	
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 316 "shams.l"
{
					fprintf(tokenout,"<LBRACKET,%s>",yytext);
					fprintf(logout,"Line no %d: TOKEN <LBRACKET> Lexeme %s found\n",line_count,yytext);
					 
					symbolInfo symbolIn(yytext,"LBRACKET");
					symtab.input(symbolIn);
					symtab.print();
			}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 324 "shams.l"
{
					fprintf(tokenout,"<RBRACKET,%s>",yytext);
					fprintf(logout,"Line no %d: TOKEN <RBRACKET> Lexeme %s found\n",line_count,yytext);
					 
					symbolInfo symbolIn(yytext,"RBRACKET");
					symtab.input(symbolIn);
					symtab.print();
			}	
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 332 "shams.l"
{
					fprintf(tokenout,"<SEMICOLON,%s>",yytext);
					fprintf(logout,"Line no %d: TOKEN <SEMICOLON> Lexeme %s found\n",line_count,yytext);
					 
					symbolInfo symbolIn(yytext,"SEMICOLON");
					symtab.input(symbolIn);
					symtab.print();
			}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 340 "shams.l"
{
					fprintf(tokenout,"<COMMA,%s>",yytext);
					fprintf(logout,"Line no %d: TOKEN <COMMA> Lexeme %s found\n",line_count,yytext);
					 
					symbolInfo symbolIn(yytext,"COMMA");
					symtab.input(symbolIn);
					symtab.print();
			}	
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 350 "shams.l"
{
					fprintf(tokenout,"<ADDOP,%s>",yytext);
					fprintf(logout,"Line no %d: TOKEN <ADDOP> Lexeme %s found\n",line_count,yytext);
					 
					symbolInfo symbolIn(yytext,"ADDOP");
					symtab.input(symbolIn);
					symtab.print();
			}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 358 "shams.l"
{
					fprintf(tokenout,"<SUBOP,%s>",yytext);
					fprintf(logout,"Line no %d: TOKEN <SUBOP> Lexeme %s found\n",line_count,yytext);
					 
					symbolInfo symbolIn(yytext,"SUBOP");
					symtab.input(symbolIn);
					symtab.print();
			}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 366 "shams.l"
{
					fprintf(tokenout,"<MULOP,%s>",yytext);
					fprintf(logout,"Line no %d: TOKEN <MULOP> Lexeme %s found\n",line_count,yytext);
					 
					symbolInfo symbolIn(yytext,"MULOP");
					symtab.input(symbolIn);
					symtab.print();
			}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 375 "shams.l"
{
					fprintf(tokenout,"<DIVOP,%s>",yytext);
					fprintf(logout,"Line no %d: TOKEN <DIVOP> Lexeme %s found\n",line_count,yytext);
					 
					symbolInfo symbolIn(yytext,"DIVOP");
					symtab.input(symbolIn);
					symtab.print();
			}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 383 "shams.l"
{
					fprintf(tokenout,"<MODOP,%s>",yytext);
					fprintf(logout,"Line no %d: TOKEN <MODOP> Lexeme %s found\n",line_count,yytext);
					 
					symbolInfo symbolIn(yytext,"MODOP");
					symtab.input(symbolIn);
					symtab.print();
			}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 391 "shams.l"
{
					fprintf(tokenout,"<ASSIGNOP,%s>",yytext);
					fprintf(logout,"Line no %d: TOKEN <ASSIGNOP> Lexeme %s found\n",line_count,yytext);
					 
					symbolInfo symbolIn(yytext,"ASSIGNOP");
					symtab.input(symbolIn);
					symtab.print();
			}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 399 "shams.l"
{
					fprintf(tokenout,"<INCOP,%s>",yytext);
					fprintf(logout,"Line no %d: TOKEN <INCOP> Lexeme %s found\n",line_count,yytext);
					 
					symbolInfo symbolIn(yytext,"INCOP");
					symtab.input(symbolIn);
					symtab.print();
			}			
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 407 "shams.l"
{
					fprintf(tokenout,"<DECOP,%s>",yytext);
					fprintf(logout,"Line no %d: TOKEN <DECOP> Lexeme %s found\n",line_count,yytext);
					 
					symbolInfo symbolIn(yytext,"DECOP");
					symtab.input(symbolIn);
					symtab.print();
			}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 415 "shams.l"
{
					fprintf(tokenout,"<RELOP,%s>",yytext);
					fprintf(logout,"Line no %d: TOKEN <RELOP> Lexeme %s found\n",line_count,yytext);
					 
					symbolInfo symbolIn(yytext,"RELOP");
					symtab.input(symbolIn);
					symtab.print();
			}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 423 "shams.l"
{
					fprintf(tokenout,"<LOGICOP,%s>",yytext);
					fprintf(logout,"Line no %d: TOKEN <LOGICOP> Lexeme %s found\n",line_count,yytext);
					 
					symbolInfo symbolIn(yytext,"LOGICOP");
					symtab.input(symbolIn);
					symtab.print();
			}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 431 "shams.l"
{
					fprintf(tokenout,"<LOGICOP,%s>",yytext);
					fprintf(logout,"Line no %d: TOKEN <LOGICOP> Lexeme %s found\n",line_count,yytext);
					 
					symbolInfo symbolIn(yytext,"LOGICOP");
					symtab.input(symbolIn);
					symtab.print();
			}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 439 "shams.l"
{
					fprintf(tokenout,"<LOGICOP,%s>",yytext);
					fprintf(logout,"Line no %d: TOKEN <LOGICOP> Lexeme %s found\n",line_count,yytext);
					 
					symbolInfo symbolIn(yytext,"LOGICOP");
					symtab.input(symbolIn);
					symtab.print();
			}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 448 "shams.l"
{
				fprintf(tokenout,"<CONST_INT,%s>",yytext);
				fprintf(logout,"Line no %d: TOKEN <CONST_INT> Lexeme %s found\n",line_count,yytext);
				 
				symbolInfo symbolIn(yytext,"CONST_INT");
                symtab.input(symbolIn);
				symtab.print();
			}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 456 "shams.l"
{
				fprintf(tokenout,"<CONST_FLOAT,%s>",yytext);
				fprintf(logout,"Line no %d: TOKEN <CONST_FLOAT> Lexeme %s found\n",line_count,yytext);
				 
				symbolInfo symbolIn(yytext,"CONST_FLOAT");
                symtab.input(symbolIn);
				symtab.print();
			}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 464 "shams.l"
{
				fprintf(tokenout,"<CONST_CHAR,%s>",yytext);
				fprintf(logout,"Line no %d: TOKEN <CONST_CHAR> Lexeme %s found\n",line_count,yytext);
				 
				symbolInfo symbolIn(yytext,"CONST_CHAR");
                symtab.input(symbolIn);
				symtab.print();
			}
	YY_BREAK
case 46:
#line 473 "shams.l"
case 47:
#line 474 "shams.l"
case 48:
#line 475 "shams.l"
case 49:
#line 476 "shams.l"
case 50:
#line 477 "shams.l"
case 51:
#line 478 "shams.l"
case 52:
#line 479 "shams.l"
case 53:
#line 480 "shams.l"
case 54:
#line 481 "shams.l"
case 55:
YY_RULE_SETUP
#line 481 "shams.l"
{
				fprintf(tokenout,"<CONST_CHAR,%s>",yytext);
				fprintf(logout,"Line no %d: TOKEN <CONST_CHAR> Lexeme %s found\n",line_count,yytext);
				 
				symbolInfo symbolIn(yytext,"CONST_CHAR");
                symtab.input(symbolIn);
				symtab.print();
			}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 489 "shams.l"
{
				printf("Valid id");
				fprintf(tokenout,"<ID,%s>",yytext);
				fprintf(logout,"Line no %d: TOKEN <ID> Lexeme %s found\n",line_count,yytext);
				 			
				symbolInfo symbolIn(yytext,"ID");
                symtab.input(symbolIn);
				symtab.print();
				
			}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 500 "shams.l"
{
					printf("Invalid ID");
				}							
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 504 "shams.l"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 2);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 165 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 2;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 165 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 164);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 504 "shams.l"


int main(int argc,char *argv[]){

	
	
	if(argc!=2){
		printf("Please provide input file name and try again\n");
		return 0;
	}
	//printf("1st: %s 2nd: %s\n\n",argv[0],argv[1]);
	FILE *fin=fopen(argv[1],"r");
	if(fin==NULL){
		printf("Cannot open specified file\n");
		return 0;
	}
	
	
	
	logout= fopen("008_log.txt","w");
	tokenout= fopen("008_token.txt","w");

	yyin= fin;
	yylex();
	
	fprintf(logout,"\nTotal Lines: %d", line_count);
	fprintf(logout,"\nTotal Errors: %d", error_count);
	
	fclose(yyin);
	fclose(tokenout);
	fclose(logout);
	
	

	return 0;
}