/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 50
#define YY_END_OF_BUFFER 51
static yyconst short int yy_accept[176] =
    {   0,
        0,    0,   51,   50,    2,    1,   30,   50,   50,   25,
       50,   48,   31,   23,   21,   35,   22,   43,   24,   37,
       34,   28,   29,   28,   40,   40,   33,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   32,   50,    2,
        0,   28,   44,    0,   42,   47,    0,   30,   48,   48,
       48,   26,   27,   43,   43,    0,   19,   43,   37,   44,
       44,   44,   45,   39,   40,   40,    0,   40,   40,   40,
       40,   40,   40,    7,   40,   40,   40,    3,   40,   40,
       40,   40,   40,   30,   44,   44,    0,    0,    0,   42,
       41,   48,   48,    0,    0,   48,   43,   43,   49,    0,

       49,   19,   38,   44,   44,   39,   39,   39,   40,    0,
       39,   40,   40,   40,   40,   40,   40,   40,   40,    5,
        6,   40,   40,   40,   40,   44,   42,   46,   41,   43,
       49,   49,   44,    0,   36,   40,   17,   15,   40,   40,
       40,    4,   40,   40,   40,    9,   40,   20,   49,    0,
       38,   36,   36,   36,   36,   13,   40,   40,   40,    8,
       40,   40,   12,   38,   36,   36,   40,   40,   14,   16,
       10,   40,   11,   18,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    6,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,    1,   20,   21,
       22,   23,    1,   24,   25,   26,   25,   26,   27,   26,
       26,   25,   26,   26,   26,   28,   26,   26,   26,   26,
       26,   29,   26,   28,   26,   26,   26,   26,   26,   26,
       30,   31,   32,   24,   33,    1,   34,   35,   36,   37,

       38,   39,   26,   40,   41,   26,   42,   43,   26,   44,
       45,   26,   26,   46,   47,   48,   49,   50,   51,   26,
       26,   26,   52,   53,   54,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[55] =
    {   0,
        1,    1,    2,    3,    1,    4,    1,    3,    1,    1,
        1,    1,    1,    1,    1,    4,    5,    6,    6,    1,
        1,    3,    1,    3,    6,    6,    6,    6,    6,    1,
        1,    1,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    1,    1,    1
    } ;

static yyconst short int yy_base[190] =
    {   0,
        0,    0,  333,  811,  327,  811,   51,   51,   68,  811,
      310,   92,  811,  811,  281,  811,  228,   42,   51,  131,
      811,  214,  203,  191,  147,  155,  811,  161,  170,   43,
      132,  147,  157,  117,  160,  169,  172,  811,  119,  152,
        0,  811,   46,  188,  811,  147,  213,    0,  220,  263,
      310,  811,  811,  204,  212,   68,    0,  208,    0,  352,
      219,  260,  298,  268,  277,  195,   60,  318,  308,  321,
      298,  329,  338,  342,  350,  354,  362,  358,  375,  376,
      377,  385,  393,  811,  180,  223,  151,  409,  408,  424,
      811,  139,  103,   92,   88,   82,  427,  431,  264,   77,

      265,    0,  435,  440,  448,  458,  234,  298,  462,  453,
      469,  397,  452,  449,  459,  466,  468,  476,  475,  478,
      485,  488,  495,  502,  510,  304,  190,  811,  811,  530,
      268,  424,  541,  382,  568,  589,  518,  590,  592,  602,
      605,  604,  612,  619,  622,  621,  634,  811,  440,  508,
      546,  513,    0,  548,    0,  635,  637,  644,  652,  651,
      654,  661,  668,  609,  622,  685,  671,  678,  685,  687,
      688,  697,  700,  704,  811,  747,  753,  756,   60,  762,
      768,  774,  780,  783,  786,   56,  792,  798,  804
    } ;

static yyconst short int yy_def[190] =
    {   0,
      175,    1,  175,  175,  175,  175,  176,  177,  176,  175,
        9,  175,  175,  175,  175,  175,  175,    9,  175,    9,
      175,  175,  175,  175,  178,  178,  175,  178,  178,   29,
       26,   29,   29,   29,   29,   29,   29,  175,  175,  175,
        9,  175,  179,  177,  175,  180,  177,    9,   12,   49,
      181,  175,  175,    9,    9,  182,  183,    9,   20,  179,
       60,  179,  175,  184,  185,   29,  175,  185,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,  175,  186,  179,  180,  180,  177,  177,
      175,   50,   49,  175,  175,   49,    9,    9,  182,  187,

      182,  183,    9,  186,   60,  184,  184,  184,  185,  175,
      184,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,  186,  180,  175,  175,    9,
      187,  188,  179,  175,  175,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,  175,  188,  175,
      186,  189,  189,  135,  135,   29,   29,   29,   29,   29,
       29,   29,   29,  175,  189,  135,   29,   29,   29,   29,
       29,   29,   29,   29,    0,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175
    } ;

static yyconst short int yy_nxt[866] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       13,   14,   15,   16,   17,   18,   19,   20,   20,   21,
       22,   23,   24,    9,   25,   25,   26,   25,   25,   27,
        4,   27,   25,   25,   28,   29,   30,   31,   32,   25,
       33,   25,   25,   25,   25,   34,   35,   25,   25,   36,
       37,   38,   39,   38,   41,   45,   41,   54,   41,   55,
       55,  126,   56,   85,   85,   86,   41,   57,   41,   41,
       46,   41,   42,   41,   41,   41,   66,  110,  110,  100,
       73,   47,   66,   41,  101,   41,   41,   74,  100,  175,
      129,   41,   49,   49,   49,   49,  128,   49,   49,   49,

      129,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,  128,   49,   49,   49,   49,   50,   50,   50,   50,
       50,   49,   51,   49,   49,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   49,   49,   49,   58,  128,   59,   59,
       66,   45,   64,   40,   80,   45,   66,   60,   61,   61,
       64,   66,   64,   61,   65,   65,   64,   67,   62,   67,
       64,   84,   68,   68,   75,   64,   64,   88,   65,   65,
       66,   88,   63,   63,   63,   64,   66,   65,   65,   76,
       66,   77,   45,   66,   45,   78,   66,   85,   85,   66,

       79,   66,   66,   70,   66,   66,   69,   46,   66,   71,
       81,   83,   42,   82,   72,   89,   66,   90,   47,   54,
       88,   97,   97,   54,   42,  103,  103,   98,   66,   55,
       55,  175,   46,  175,   66,   42,   85,   85,   62,   66,
       85,   85,   53,   47,   49,   49,   49,   49,   49,   62,
       49,  107,  107,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   91,   67,  106,   67,  131,  131,  104,  104,  131,
      101,  101,   64,  106,  148,  107,  107,   92,   92,   92,
       92,   92,   64,   52,   65,   65,   92,   92,   92,   92,

       92,   92,   92,   92,   92,   92,   92,   92,   92,   92,
       92,   92,   92,   92,   94,  107,  107,   48,   95,   96,
       96,   85,   85,   64,   63,   63,   63,   96,   40,   95,
       63,  114,  175,  111,   49,   68,   68,   66,   49,  175,
       96,   66,   66,   96,   96,  112,  175,   66,   96,   63,
       63,   63,   66,   96,   66,   96,  175,   96,  175,   96,
       66,   49,   66,   49,   67,   66,   67,  113,   66,  104,
      104,   66,  115,   66,  175,   66,  116,   66,  105,  105,
      105,   66,   66,   66,  105,  175,   66,   66,  175,   66,
      117,   66,  175,   66,   66,   66,  118,   66,  119,  152,

      152,   66,   66,   63,   63,   63,   66,  120,   66,   66,
       66,   87,   45,  127,   66,   66,   66,  123,   66,   66,
       66,   66,  121,  122,   66,  124,   66,   46,   45,   66,
      136,  175,   66,  125,  175,  131,   66,   66,   47,   88,
      101,   66,   54,   46,   97,   97,   54,  175,  130,  130,
       98,  131,  103,  103,   47,  134,  101,  104,  104,  175,
      175,  133,  175,  106,  175,   85,   85,   64,  134,  175,
      110,  110,   62,  106,  106,  107,  107,   64,  175,   65,
       65,  175,   66,  175,  106,   66,  135,  135,   66,  137,
      175,   66,   66,   66,  138,  175,   66,  175,   66,  140,

      175,   66,  141,   66,  175,   66,  139,   66,  143,   66,
       66,   66,   66,  142,   66,   66,  175,   66,   66,   66,
       66,   66,   66,  175,   66,  164,  164,   66,   66,   66,
      165,  165,   66,  175,   66,   66,  144,  175,  146,   66,
      175,   66,  145,   66,  175,   98,   66,  130,  130,   66,
      175,   66,  147,  150,   66,  150,   62,   66,  151,  151,
      175,  134,   66,  151,  151,  166,  166,   62,  153,  153,
      175,  153,  153,  154,  153,  153,  153,  153,  153,  153,
      153,  153,  153,  154,  153,  155,  155,  153,  153,  153,
      153,  153,  154,  154,  154,  154,  154,  153,  153,  153,

      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  153,
      153,  153,   66,   66,  134,   66,  164,  164,   66,   66,
      156,   66,  157,   66,   66,   66,   66,   66,   66,  165,
      165,   66,  175,   66,   66,   66,   66,  159,   66,   66,
      158,   66,   66,  175,   66,   66,   66,  162,   66,  160,
       66,   66,  175,   66,  161,   66,   66,   66,   66,  175,
       66,  163,  175,   66,   66,  175,   66,   66,   66,   66,
      167,   66,  175,   66,   66,   66,  168,   66,   66,  169,
       66,   66,  175,   66,   66,   66,   66,  170,   66,  175,

      171,   66,  166,  166,   66,   66,  175,   66,  175,  175,
       66,   66,   66,  175,  175,   66,  175,   66,   66,  172,
       66,   66,   66,  175,   66,  173,   66,   66,  175,   66,
       66,   66,   66,   66,  174,  175,   66,   66,  175,   66,
      175,   66,  175,   66,   66,  175,  175,  175,   66,   43,
       43,  175,   43,   44,  175,   44,   44,   44,   44,   66,
      175,   66,   87,  175,   87,   87,   87,   87,   93,   93,
       93,   93,   93,   93,   99,   99,   99,   99,   99,   99,
      102,  175,  102,  102,  102,  102,  108,  175,  108,  109,
      175,  109,  132,  132,  132,  132,  175,  132,  149,  149,

      149,  149,  149,  149,  153,  175,  153,  153,  153,  153,
        3,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175
    } ;

static yyconst short int yy_chk[866] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    7,    8,    7,   18,    7,   18,
       18,  186,   19,   43,   43,  179,    7,   19,    7,    7,
        8,    9,    7,    9,    7,    9,   30,   67,   67,   56,
       30,    8,   30,    9,   56,    9,    9,   30,  100,    9,
       96,    9,   12,   12,   12,   12,   95,   12,   12,   12,

       94,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   93,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   20,   92,   20,   20,
       34,   46,   25,   40,   34,   87,   34,   20,   20,   20,
       26,   34,   25,   20,   25,   25,   28,   26,   20,   26,
       26,   39,   26,   26,   31,   29,   28,   46,   28,   28,
       32,   87,   20,   20,   20,   29,   32,   29,   29,   32,
       33,   32,   44,   35,  127,   33,   33,   85,   85,   35,

       33,   33,   36,   29,   35,   37,   28,   44,   36,   29,
       35,   37,   24,   36,   29,   47,   37,   47,   44,   54,
      127,   54,   54,   58,   23,   58,   58,   55,   66,   55,
       55,   61,   47,   61,   66,   22,   61,   61,   55,   66,
       86,   86,   17,   47,   49,   49,   49,   49,   49,   55,
       49,  107,  107,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   50,   62,   64,   62,   99,  101,   62,   62,  131,
       99,  101,   65,   64,  131,   64,   64,   50,   50,   50,
       50,   50,   65,   15,   65,   65,   50,   50,   50,   50,

       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   51,  108,  108,   11,   51,   51,
       51,  126,  126,   68,   63,   63,   63,   51,    5,   51,
       63,   71,    3,   68,   51,   68,   68,   71,   51,    0,
       51,   69,   71,   51,   51,   69,    0,   69,   51,   63,
       63,   63,   69,   51,   70,   51,    0,   51,    0,   51,
       70,   51,   72,   51,   60,   70,   60,   70,   72,   60,
       60,   73,   72,   72,    0,   74,   73,   73,   60,   60,
       60,   74,   73,   75,   60,    0,   74,   76,    0,   75,
       74,   78,    0,   76,   75,   77,   75,   78,   76,  134,

      134,   77,   78,   60,   60,   60,   77,   77,   79,   80,
       81,   88,   89,   88,   79,   80,   81,   81,   82,   79,
       80,   81,   79,   80,   82,   82,   83,   89,   90,   82,
      112,    0,   83,   83,    0,  132,  112,   83,   89,   88,
      132,  112,   97,   90,   97,   97,   98,    0,   98,   98,
      103,  149,  103,  103,   90,  104,  149,  104,  104,    0,
      105,  103,  105,  106,    0,  105,  105,  109,  110,    0,
      110,  110,  103,  106,  111,  106,  106,  109,    0,  109,
      109,    0,  114,    0,  111,  113,  111,  111,  114,  113,
        0,  113,  115,  114,  114,    0,  113,    0,  115,  116,

        0,  117,  117,  115,    0,  116,  115,  117,  119,  118,
      116,  120,  117,  118,  119,  118,    0,  120,  121,  119,
      118,  122,  120,    0,  121,  150,  150,  122,  123,  121,
      152,  152,  122,    0,  123,  124,  122,    0,  124,  123,
        0,  124,  123,  125,    0,  130,  124,  130,  130,  125,
        0,  137,  125,  133,  125,  133,  130,  137,  133,  133,
        0,  151,  137,  151,  151,  154,  154,  130,  135,  135,
        0,  135,  135,  135,  135,  135,  135,  135,  135,  135,
      135,  135,  135,  135,  135,  135,  135,  135,  135,  135,
      135,  135,  135,  135,  135,  135,  135,  135,  135,  135,

      135,  135,  135,  135,  135,  135,  135,  135,  135,  135,
      135,  135,  135,  135,  135,  135,  135,  135,  135,  135,
      135,  135,  136,  138,  164,  139,  164,  164,  136,  138,
      136,  139,  139,  136,  138,  140,  139,  142,  141,  165,
      165,  140,    0,  142,  141,  143,  140,  141,  142,  141,
      140,  143,  144,    0,  146,  145,  143,  145,  144,  143,
      146,  145,    0,  144,  144,  146,  145,  147,  156,    0,
      157,  147,    0,  147,  156,    0,  157,  158,  147,  156,
      157,  157,    0,  158,  160,  159,  158,  161,  158,  159,
      160,  159,    0,  161,  162,  160,  159,  161,  161,    0,

      162,  163,  166,  166,  167,  162,    0,  163,    0,    0,
      167,  168,  163,    0,    0,  167,    0,  168,  169,  167,
      170,  171,  168,    0,  169,  168,  170,  171,    0,  169,
      172,  170,  171,  173,  172,    0,  172,  174,    0,  173,
        0,  172,    0,  174,  173,    0,    0,    0,  174,  176,
      176,    0,  176,  177,    0,  177,  177,  177,  177,  178,
        0,  178,  180,    0,  180,  180,  180,  180,  181,  181,
      181,  181,  181,  181,  182,  182,  182,  182,  182,  182,
      183,    0,  183,  183,  183,  183,  184,    0,  184,  185,
        0,  185,  187,  187,  187,  187,    0,  187,  188,  188,

      188,  188,  188,  188,  189,    0,  189,  189,  189,  189,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "mila.l"
#define INITIAL 0
#line 4 "mila.l"
#include<stdio.h>
#include<stdlib.h>
#include<bits/stdc++.h>
using namespace std;

int line_count=1;
int error=0;

FILE *logout;
FILE *tokenout;
#define MOD 1001
#define SIZE 1001

int hash_func(string str)
{
    int i,len=str.length();
    int hash=0;
    for(i=0; i<len; i++)
    {
        hash += str[i]^i * 27;
        hash %= MOD;
    }
    return hash;
}

class symbolInfo
{
public:
    string name;
    string type;

    symbolInfo(string n,string t){
        name=n;
        type=t;
    }
};

class symbolTable
{
public:
    vector <symbolInfo> stable[SIZE];
    int count1;
	bool lookup(string name,string type){
        int key=hash_func(name);
        count1=0;

        vector<symbolInfo> ::iterator it;
        for(it=stable[key].begin() ; it!=stable[key].end() ;it++){
            if(it->name == name)
                return true;
                count1++;
        }
        return false;
    }
	void insert (string name,string type){
        int key=hash_func(name);
        if(lookup(name,type)==true){
			fprintf(logout,"already inserted.\n\n");
            return;
        }
            symbolInfo e(name,type);
            stable[key].push_back(e);
    }
	void print(){
        int i,j;
        vector<symbolInfo>::iterator it;
        for(i=0;i<SIZE ;i++){
            if(stable[i].size()==0)
                continue;
			fprintf(logout,"%d -->  ",i);
            for(it=stable[i].begin();it!=stable[i].end();it++){
				string tp=it->type;
				string nm= it->name;
				char *n=new char[nm.length()+1];
				char  *t=new char [tp.length()+1];
				
				for(j=0;j<tp.length();j++)
				t[j]=tp[j];
				t[j]='\0';
				
				for(j=0;j<nm.length();j++)
				n[j]=nm[j];
				n[j]='\0';
				fprintf(logout,"< %s,%s >",n,t);
				//cout<<"name"<<it->name<<endl;
            }
			fprintf(logout,"\n");
			
        }
		fprintf(logout,"\n\n");
    }
};
symbolTable symtab;


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 125 "mila.l"



	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 176 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 811 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 127 "mila.l"
{line_count++;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 128 "mila.l"
{}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 130 "mila.l"
{
			fprintf(tokenout,"<IF>");
			fprintf(logout,"Line no %d: TOKEN <IF> Lexeme %s found\n\n",line_count,yytext);
		}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 135 "mila.l"
{
			fprintf(tokenout,"<ELSE>");
			fprintf(logout,"Line no %d: TOKEN <ELSE> Lexeme %s found\n\n",line_count,yytext);
		}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 139 "mila.l"
{
			fprintf(tokenout,"<FOR>");
			fprintf(logout,"Line no %d: TOKEN <FOR> Lexeme %s found\n\n",line_count,yytext);
		}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 143 "mila.l"
{
			fprintf(tokenout,"<INT>");
			fprintf(logout,"Line no %d: TOKEN <INT> Lexeme %s found\n\n",line_count,yytext);
		}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 148 "mila.l"
{
			fprintf(tokenout,"<DO>");
			fprintf(logout,"Line no %d: TOKEN <DO> Lexeme %s found\n\n",line_count,yytext);
		}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 152 "mila.l"
{
			fprintf(tokenout,"<FLOAT>");
			fprintf(logout,"Line no %d: TOKEN <FLOAT> Lexeme %s found\n\n",line_count,yytext);
		}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 156 "mila.l"
{
			fprintf(tokenout,"<VOID>");
			fprintf(logout,"Line no %d: TOKEN <VOID> Lexeme %s found\n\n",line_count,yytext);
		}		
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 160 "mila.l"
{
			fprintf(tokenout,"<SWITCH>");
			fprintf(logout,"Line no %d: TOKEN <SWITCH> Lexeme %s found\n\n",line_count,yytext);
		}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 164 "mila.l"
{
			fprintf(tokenout,"<DEFAULT>");
			fprintf(logout,"Line no %d: TOKEN <DEFAULT> Lexeme %s found\n\n",line_count,yytext);
		}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 168 "mila.l"
{
			fprintf(tokenout,"<WHILE>");
			fprintf(logout,"Line no %d: TOKEN <WHILE> Lexeme %s found\n\n",line_count,yytext);
		}		
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 172 "mila.l"
{
			fprintf(tokenout,"<BREAK>");
			fprintf(logout,"Line no %d: TOKEN <BREAK> Lexeme %s found\n\n",line_count,yytext);
		}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 176 "mila.l"
{
			fprintf(tokenout,"<DOUBLE>");
			fprintf(logout,"Line no %d: TOKEN <DOUBLE> Lexeme %s found\n\n",line_count,yytext);
		}		
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 180 "mila.l"
{
			fprintf(tokenout,"<CHAR>");
			fprintf(logout,"Line no %d: TOKEN <CHAR> Lexeme %s found\n\n",line_count,yytext);
		}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 185 "mila.l"
{
			fprintf(tokenout,"<RETURN>");
			fprintf(logout,"Line no %d: TOKEN <RETURN> Lexeme %s found\n\n",line_count,yytext);
		}		
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 189 "mila.l"
{
			fprintf(tokenout,"<CASE>");
			fprintf(logout,"Line no %d: TOKEN <CASE> Lexeme %s found\n\n",line_count,yytext);
		}	
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 194 "mila.l"
{
			fprintf(tokenout,"<CONTINUE>");
			fprintf(logout,"Line no %d: TOKEN <CONTINUE> Lexeme %s found\n\n",line_count,yytext);
		}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 198 "mila.l"
{
			fprintf(tokenout,"<COMMENT>");
			fprintf(logout,"Line no %d: TOKEN <COMMENT> Lexeme %s found\n\n",line_count,yytext);
			line_count++;
			}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 203 "mila.l"
{
			fprintf(tokenout,"<COMMENT>");
			fprintf(logout,"Line no %d: TOKEN <COMMENT> Lexeme %s found\n\n",line_count+1,yytext);
			line_count++;
			}
	YY_BREAK
case 21:
#line 212 "mila.l"
case 22:
YY_RULE_SETUP
#line 213 "mila.l"
{
			fprintf(tokenout,"<ADDOP,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <ADDOP> Lexeme %s found\n\n",line_count,yytext);
			string t="ADDOP";
			symtab.insert(yytext,t);
			symtab.print();
			//insert in symbol table and print symbol table content(only non empty buckets)
			// There is a '|' in "+"'s rule, this means match execute the action for following rule
		}
	YY_BREAK
case 23:
#line 223 "mila.l"
case 24:
#line 224 "mila.l"
case 25:
YY_RULE_SETUP
#line 224 "mila.l"
{
			fprintf(tokenout,"<MULOP,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <MULOP> Lexeme %s found\n\n",line_count,yytext);
			string t="MULOP";
			symtab.insert(yytext,t);
			symtab.print();
		}
	YY_BREAK
case 26:
#line 232 "mila.l"
case 27:
YY_RULE_SETUP
#line 232 "mila.l"
{
			fprintf(tokenout,"<INCOP,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <INCOP> Lexeme %s found\n\n",line_count,yytext);
			string t="INCOP";
			symtab.insert(yytext,t);
			symtab.print();
		}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 239 "mila.l"
{
			fprintf(tokenout,"<RELOP,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <RELOP> Lexeme %s found\n\n",line_count,yytext);
			string t="RELOP";
			symtab.insert(yytext,t);
			symtab.print();
		}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 246 "mila.l"
{
			fprintf(tokenout,"<ASSIGNOP,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <ASSIGNOP> Lexeme %s found\n\n",line_count,yytext);
			string t="ASSIGNOP";
			symtab.insert(yytext,t);
			symtab.print();
		}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 253 "mila.l"
{
			fprintf(tokenout,"<LOGOP,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <LOGOP> Lexeme %s found\n\n",line_count,yytext);
			string t="LOGOP";
			symtab.insert(yytext,t);
			symtab.print();
			}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 260 "mila.l"
{
			fprintf(tokenout,"<PAREN,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <PAREN> Lexeme %s found\n\n",line_count,yytext);
			string t="PAREN";
			symtab.insert(yytext,t);
			symtab.print();
			}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 267 "mila.l"
{
			fprintf(tokenout,"<CURL,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <CURL> Lexeme %s found\n\n",line_count,yytext);
			string t="CURL";
			symtab.insert(yytext,t);
			symtab.print();
			}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 274 "mila.l"
{
			fprintf(tokenout,"<BRACKET,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <BRACKET> Lexeme %s found\n\n",line_count,yytext);
			string t="BRACKET";
			symtab.insert(yytext,t);
			symtab.print();
			}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 281 "mila.l"
{
			fprintf(tokenout,"<SEMICOLON,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <SEMICOLON> Lexeme %s found\n\n",line_count,yytext);
			string t="SEMICOLON";
			symtab.insert(yytext,t);
			symtab.print();
		}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 288 "mila.l"
{
			fprintf(tokenout,"<COMMA,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <COMMA> Lexeme %s found\n\n",line_count,yytext);
			string t="COMMA";
			symtab.insert(yytext,t);
			symtab.print();
		}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 295 "mila.l"
{
				fprintf(logout,"Error at Line no %d: Ill formed of number such as %s .\n\n",line_count,yytext);
				error++;
			}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 300 "mila.l"
{
				fprintf(tokenout,"<CONST_INT,%s>",yytext);
				fprintf(logout,"Line    no %d: TOKEN <CONST_INT> Lexeme %s found\n\n",line_count,yytext);
				string t="CONST_INT";
				symtab.insert(yytext,t);
				symtab.print();
				//insert in symbol table and print symbol table content(only non empty buckets)
			}			
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 309 "mila.l"
{
				fprintf(tokenout,"<CONST_FLOAT,%s>",yytext);
				fprintf(logout,"Line no %d: TOKEN <CONST_FLOAT> Lexeme %s found\n\n",line_count,yytext);
				string t="CONST_FLOAT";
				symtab.insert(yytext,t);
				symtab.print();
				//insert in symbol table and print symbol table content(only non empty buckets)
			}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 317 "mila.l"
{
				fprintf(logout,"Error at Line no %d: INVALID IDENTIFIER %s .\n\n",line_count,yytext);
				error++;
			}			
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 321 "mila.l"
{
				fprintf(tokenout,"<ID,%s>",yytext);
				fprintf(logout,"Line no %d: TOKEN <ID> Lexeme %s found\n\n",line_count,yytext);
				string t="ID";
				symtab.insert(yytext,t);
				symtab.print();
			}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 329 "mila.l"
{
				fprintf(tokenout,"<CONST_CHAR,%s>",yytext);
				fprintf(logout,"Line no %d: TOKEN <CONST_CHAR> Lexeme %s found\n\n",line_count,yytext);
				string t="CONST_CHAR";
				symtab.insert(yytext,t);
				symtab.print();
			   }			
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 336 "mila.l"
{   fprintf(tokenout,"<STRING,%s>",yytext);
				fprintf(logout,"Line no %d: TOKEN <STRING> Lexeme %s found\n\n",line_count,yytext);
			}	
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 339 "mila.l"
{
				fprintf(logout,"Error at Line no %d: Too many decimal points %s .\n\n",line_count,yytext);
				error++;
			}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 343 "mila.l"
{
				fprintf(logout,"Error at Line no %d: Invalid prefix %s .\n\n",line_count,yytext);
				error++;
			}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 347 "mila.l"
{
				fprintf(logout,"Error at Line no %d: Invalid suffix %s .\n\n",line_count,yytext);
				error++;
			}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 351 "mila.l"
{
				fprintf(logout,"Error at Line no %d: Multicharacter constant error for character sequence %s .\n\n",line_count,yytext);
				error++;
			}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 355 "mila.l"
{
				fprintf(logout,"Error at Line no %d: Unfinished string %s .\n\n",line_count,yytext);
				error++;
			}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 359 "mila.l"
{
				fprintf(logout,"Error at Line no %d: Unfinished character %s .\n\n",line_count,yytext);
				error++;
			}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 363 "mila.l"
{
				fprintf(logout,"Error at Line no %d: Unfinished comment %s .\n\n",line_count,yytext);
				error++;
			}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 369 "mila.l"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 176 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 176 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 175);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 369 "mila.l"


int main(int argc,char *argv[]){
	
	if(argc!=2){
		printf("Please provide input file name and try again\n");
		return 0;
	}
	//printf("1st: %s 2nd: %s\n\n",argv[0],argv[1]);
	FILE *fin=fopen(argv[1],"r");
	if(fin==NULL){
		printf("Cannot open specified file\n");
		return 0;
	}
	
	logout= fopen("201514021_log.txt","w");
	tokenout= fopen("201514021_token.txt","w");

	yyin= fin;
	yylex();
	fprintf(logout,"Total number of line : %d .\n",line_count);
	fprintf(logout,"Total number of errors : %d .\n",error);
	fclose(yyin);
	fclose(tokenout);
	fclose(logout);
	return 0;
}